menu:
  Home: /
  Archives: archives
  cate: cate
  page:
    归档: archives
    专题: categories
#    友链: friendlinks
    关于: life
    搜索: search

sidePic: /assets/user/sidePic2.jpg
avatar: /assets/user/avatar2.jpg

excerpt_link: 继续阅读
excerpt: 200

social:
  twitter: true
  github: true
  weibo: false
  yuque: true
  rss: true

#twitter:
#  username:

github:
  username: s-xianyu

weibo:
  username: 2391745125/profile?rightmod=1&wvr=6&mod=personinfo

yuque:
  username: s-xianyu

# https://www.leancloud.cn/
valine:
  appId:
  appKey:

# https://web.umeng.com/
umeng: 1276809529
